version: "3.8"

services:
  covid-symptom-annotator:
    image: docker.synapse.org/syn22277123/covid-symptom-annotator-example:1.2.0
    build:
      context: server
      dockerfile: Dockerfile
    container_name: covid-symptom-annotator
    networks:
      - nlp-sandbox-internal

  nginx:
    image: nginx:1.19.6-alpine
    container_name: nginx
    restart: always
    environment:
      - TOOL_HOST=covid-symptom-annotator
      - TOOL_PORT=8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
    networks:
      - nlp-sandbox
      - nlp-sandbox-internal
    ports:
      - "80:80"
    depends_on:
      - covid-symptom-annotator

networks:
  nlp-sandbox:
  nlp-sandbox-internal:
    internal: true
