# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.text_covid_symptom_annotation import TextCovidSymptomAnnotation
from openapi_server import util

from openapi_server.models.text_covid_symptom_annotation import TextCovidSymptomAnnotation  # noqa: E501

class TextCovidSymptomAnnotationResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text_covid_symptom_annotations=None):  # noqa: E501
        """TextCovidSymptomAnnotationResponse - a model defined in OpenAPI

        :param text_covid_symptom_annotations: The text_covid_symptom_annotations of this TextCovidSymptomAnnotationResponse.  # noqa: E501
        :type text_covid_symptom_annotations: List[TextCovidSymptomAnnotation]
        """
        self.openapi_types = {
            'text_covid_symptom_annotations': List[TextCovidSymptomAnnotation]
        }

        self.attribute_map = {
            'text_covid_symptom_annotations': 'textCovidSymptomAnnotations'
        }

        self._text_covid_symptom_annotations = text_covid_symptom_annotations

    @classmethod
    def from_dict(cls, dikt) -> 'TextCovidSymptomAnnotationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextCovidSymptomAnnotationResponse of this TextCovidSymptomAnnotationResponse.  # noqa: E501
        :rtype: TextCovidSymptomAnnotationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text_covid_symptom_annotations(self):
        """Gets the text_covid_symptom_annotations of this TextCovidSymptomAnnotationResponse.

        A list of COVID symptom annotations  # noqa: E501

        :return: The text_covid_symptom_annotations of this TextCovidSymptomAnnotationResponse.
        :rtype: List[TextCovidSymptomAnnotation]
        """
        return self._text_covid_symptom_annotations

    @text_covid_symptom_annotations.setter
    def text_covid_symptom_annotations(self, text_covid_symptom_annotations):
        """Sets the text_covid_symptom_annotations of this TextCovidSymptomAnnotationResponse.

        A list of COVID symptom annotations  # noqa: E501

        :param text_covid_symptom_annotations: The text_covid_symptom_annotations of this TextCovidSymptomAnnotationResponse.
        :type text_covid_symptom_annotations: List[TextCovidSymptomAnnotation]
        """
        if text_covid_symptom_annotations is None:
            raise ValueError("Invalid value for `text_covid_symptom_annotations`, must not be `None`")  # noqa: E501

        self._text_covid_symptom_annotations = text_covid_symptom_annotations
